### ISSUE TITLE
后台20分钟左右没有活动连接自动断开

### ISSUE THREAD

**Issue by wjfu99** [Mythologyli/zju-connect#13]
目前多次测试发现，连接上vpn服务器正常使用后，当vpn后台无任何活动连接超过20分钟左右就会出现以下error。不太清楚这个是bug还是什么，重连后可以恢复正常。（华中科技大学vpn测试，使用原版Easierconnect存在同样情况）

<img width="558" alt="image" src="https://user-images.githubusercontent.com/57850011/220126042-34c9c1b3-214e-42f5-8b0d-99002d3cecba.png">
<img width="558" alt="image" src="https://user-images.githubusercontent.com/57850011/220125628-ed3f6bb1-5def-41b4-b856-956e942d3254.png">

估计使用自动重连脚本可以实现自动重连，但目测会导致ssh连接直接断开，强迫症不太能接受。不知道大佬能不能修复一下，或者告诉一下原因或修复问题的方向，打算尝试折腾一下（虽然不懂go语言），谢谢。

**Comment by Mythologyli** [comment]
目前浙大的 SSLVPN 使用时没有出现这么短的掉线，猜测可能与服务端设置有关？

可以尝试写一个脚本定时使用 SOCKS5，如果不再掉线证明可以通过定时产生流量来保活，未来可在程序中添加此功能。

**Comment by Geniucker** [comment]
是不是其实也可以在服务器定时过socks5 curl一下学校的官网或者其他内网的地址🫣

**Comment by Mythologyli** [comment]
目前打算定时向校内的 DNS 服务器发起请求来保活，考虑通过一个参数设定校内 DNS 服务器的地址。你觉得这个方案可行吗？

**Comment by Geniucker** [comment]
我觉得挺好

**Comment by Mythologyli** [comment]
可以尝试使用 master 分支的最新版：https://github.com/Mythologyli/zju-connect/actions/runs/4269229527

**Comment by Mythologyli** [comment]
> > 可以尝试使用 master 分支的最新版：https://github.com/Mythologyli/zju-connect/actions/runs/4269229527
> 
> 收到，感谢， 👌我来测试一下。

欢迎测试，需要正确设置 `zju-dns-server` 参数为校内 DNS 服务器

**Comment by wjfu99** [comment]
经半天测试，目前没有发现问题，感谢🙏。

**Comment by Mythologyli** [comment]
暂时关闭，如遇问题可再次开启
