### ISSUE TITLE
恢复 AGPLv3 许可证

### ISSUE THREAD

**Issue by Hagb** [Mythologyli/zju-connect#14]
感谢 @Mythologyli 继续维护这个项目。在 https://github.com/lyc8503/EasierConnect/commit/78f56254f12351bb2b1121e3b237da181ca61fc1 中，原作者“撤回了 AGPLv3”，事实上 AGPLv3 是无法撤回的：

1. 版权所有者可以以他希望的许可证发布他的软件，但是对于之前使用 AGPLv3 发布的版本授予用户的权利，作者无法撤回。
2. 在 https://github.com/lyc8503/EasierConnect/commit/78f56254f12351bb2b1121e3b237da181ca61fc1 之前 EasierConnect 已经经过其他人的贡献，有其他人的代码合并进仓库中。而原作者如果希望使用与 AGPLv3 不兼容的授权发布新版本，则要么移除这部分代码，要么得到这部分代码的版权所有者（贡献者）的允许或者版权转让，所以其实 https://github.com/lyc8503/EasierConnect/commit/78f56254f12351bb2b1121e3b237da181ca61fc1 的版本是有许可证问题的。

此外，无许可证仓库没有明确赋予用户权利，甚至使用、贡献该项目也并不是被明确授权的。因此我建议恢复 AGPLv3 许可证（revert 7b4df3fc8e3a2902c02b88afa24cbfe1e88cc6b2，甚至通过 rebase 将 7b4df3fc8e3a2902c02b88afa24cbfe1e88cc6b2 去除），同时这（更改回 AGPLv3 许可证）还需要 @cxz66666 @kasperis7 （在无许可证下提交代码的贡献者）的同意。

以上只是我的一些愚见，再次感谢贡献者们维护这个项目。

**Comment by Mythologyli** [comment]
感谢提出此问题！

现在准备恢复 AGPLv3 许可证，征询 @cxz66666 @kasperis7 两位贡献者的意见。

**Comment by kasperis7** [comment]
我没意见。

**Comment by cxz66666** [comment]
抱歉昨日未查看zju邮箱，我没意见
