### ISSUE TITLE
可以添加 Docker 支持吗

### ISSUE THREAD

**Issue by 117503445** [Mythologyli/zju-connect#16]

**Comment by Mythologyli** [comment]
有一个将 EasyConnect 封印在 Docker 中的项目：https://github.com/Hagb/docker-easyconnect

我不太会 Docker，欢迎 PR

**Comment by Geniucker** [comment]
你自己开个ubuntu或者小一点的alpine镜像，然后在里面下载或导入对应架构的linux可执行文件，然后修改一下容器的启动参数就行了（doge）可能说了和没说一样

**Comment by lyc8503** [comment]
静态编译的 Go 文件应该可以直接复制进 Docker 的 distroless 镜像中运行, Dockerfile 可能就两三行, 如果要做从源码直接 build 的 Dockerfile 的话可能导致镜像体积严重膨胀, 感觉不是很必要. 需要的话可以自己下载二进制构建 Docker image?

**Comment by 117503445** [comment]
对我而言，Docker 有以下好处

1. 取代 Systemd 的 后台运行、自启动 等管理功能
2. 可以很方便的进行更新

**Comment by 117503445** [comment]
> 静态编译的 Go 文件应该可以直接复制进 Docker 的 distroless 镜像中运行, Dockerfile 可能就两三行, 如果要做从源码直接 build 的 Dockerfile 的话可能导致镜像体积严重膨胀, 感觉不是很必要. 需要的话可以自己下载二进制构建 Docker image?

可以用多阶段构建来规避体积膨胀的问题

**Comment by lyc8503** [comment]
> 对我而言，Docker 有以下好处
> 
> 1. 取代 Systemd 的 后台运行、自启动 等管理功能
> 2. 可以很方便的进行更新

因为部分组织登录的时候需要短信验证码登录, 所以需要人类交互(因网络不稳定被登出的时候也要), 容器容易挂, 且不能自动重新登录. 所以随开随用, 手动交互相对方便一些. 如果 ZJU 不需要短信验证码的话感觉用 Docker 可能方便一些~

**Comment by DL53** [comment]
> 有一个将 EasyConnect 封印在 Docker 中的项目：https://github.com/Hagb/docker-easyconnect
> 
> 我不太会 Docker，欢迎 PR

这个我用了发现老是断连，不知道是不是ZJUrvpn特色。。

**Comment by 117503445** [comment]
see #22 ,#23
