### ISSUE TITLE
Docker无法使用

### ISSUE THREAD

**Issue by DL53** [Mythologyli/zju-connect#24]
使用命令行导入到openwrt的docker里，默认会新建一个config.toml的文件夹，删除这个文件夹改成配置文件，或者在文件夹里放一个同名的配置文件都无法成功连接上（可以启动，但是不会形成代理服务器）

**Comment by cxz66666** [comment]
请参考此issue https://github.com/moby/moby/issues/21612 

> In terms of mounting a file, the right way to do this is to make sure a file exists before running your container

解决方法是请在当前目录下创建config.toml配置文件，之后再使用docker run启动容器，该文件将作为启动的配置文件
