### ISSUE TITLE
openwrt中passwall的dns配置 & 指定日志与配置热重载

### ISSUE THREAD

**Issue by MkQtS** [Mythologyli/zju-connect#26]
刚在OpenWrt上跑起来，有几个小问题

1. 似乎不能配置日志输出位置，会占用shell无法输入
2. 没找到断开连接/停止程序的参数

虽然可以通过linux系统的输出重定向、kill解决问题，还是不太方便，希望能支持手动加参数设置。

然后，我是用zju-connect连上RVPN，在passwall中连接本机socks节点，然后将zju域名分流至该节点，但相关域名DNS解析使用的还是passwall中设置的代理dns，请问应该如何解决呢？

**Comment by cxz66666** [comment]
1. zju-connect更多是作为一个前台进程，如果你需要将其配置成后台服务进程，请参考openwrt中procd的写法自己编写procd配置
2. 断开连接具体指的是什么呢，ctrl+c是可以结束程序的

**Comment by cxz66666** [comment]
我猜测你可以通过将cc98.org *.zju.edu.cn等域名加入passwall中->规则列表->代理列表中，同时配合配置zju域名的V2ray分流规则

**Comment by cxz66666** [comment]
wow，欢迎pr或在讨论里贡献一个openwrt上使用passwall/openclash配合zju-connect的教程😋😋
