### ISSUE TITLE
手机短信验证码登录无效

### ISSUE THREAD

**Issue by ISDHN** [Mythologyli/zju-connect#28]
登录后需要输入验证码，但是图形客户端没有验证码输入之所。

**Comment by ISDHN** [comment]
没有
请问怎么配置

**Comment by Mythologyli** [comment]
使用 switchyomega

**Comment by ISDHN** [comment]
通了
十分感谢 orz

**Comment by ISDHN** [comment]
在有验证码时，easier connect可用，本项目不可用

**Comment by Mythologyli** [comment]
本项目有自动选线功能，本质上进行了两次登录，所以需要输入两次验证码。
可以通过加 `-disable-multi-line` 参数禁用自动选线功能。
考虑到本校人员几乎不需要验证码登录（需要验证码的是运维账号，这部分人员也不需要 GUI），暂不考虑在 GUI 中添加验证码输入功能。
