### ISSUE TITLE
程序报错：0.0.0.0 -> PROXY, [E]: target addr 0.0.0.0:0

### ISSUE THREAD

**Issue by Mythologyli** [Mythologyli/zju-connect#29]
用户反馈，在 OpenWrt 上配合 PassWall 使用时，程序报错：
![image](https://github.com/Mythologyli/zju-connect/assets/15955880/d94c0a6f-5694-4be3-b0fb-0b362c327673)

配置文件：
![image](https://github.com/Mythologyli/zju-connect/assets/15955880/eccb0164-d8ed-4c76-9a90-3a8dea7f7d76)

**Comment by Mythologyli** [comment]
报错不一定会使程序崩溃：
![image](https://github.com/Mythologyli/zju-connect/assets/15955880/952c6bb6-8970-4f82-9385-5b3ccf717eab)

初步定位问题：收到了目标为 0.0.0.0:0 的 UDP 请求

**Comment by cxz66666** [comment]
有点神秘，看起来udp packet 0.0.0.0:0 并不一定导致程序崩溃吗

**Comment by Mythologyli** [comment]
对，似乎有时候崩溃有时候不崩溃
流量确定是从 passwall 来的，去掉 passwall 规则后没有收到请求

**Comment by Mythologyli** [comment]
请求也不来自 port_forwarding 中的 DNS 端口转发，去掉此转发后仍然出现相同错误

**Comment by cxz66666** [comment]
我认为可行 😄 ，后续我也排查一下为啥有时候会挂掉

**Comment by cxz66666** [comment]
排查了一下，https://github.com/things-go/go-socks5 实现的基于socks的udp代理实现细节上有问题，作者可能没分清BND.ADDR字段的作用，在握手阶段的 **0.0.0.0:0** 的含义是允许任意port和ip作为udp代理的client（发起方），作者误以为BND.ADDR是代理的目的地址

> The DST.ADDR and DST.PORT fields contain the address and port that the client expects
   to use to send UDP datagrams on for the association.  The server MAY
   use this information to limit access to the association.  If the
   client is not in possesion of the information at the time of the UDP
   ASSOCIATE, the client MUST use a port number and address of all
   zeros.


具体影响socks代理中的udp代理服务（无法正常使用），udp forward和基于udp的dns完全不受影响，影响范围较小，我尽快给go-socks5提个pr 😢

**Comment by cxz66666** [comment]
已向上游提交pr https://github.com/things-go/go-socks5/pull/33 ，希望能尽快合并 :😇
