### ISSUE TITLE
GUI 版 报错

### ISSUE THREAD

**Issue by uoht** [Mythologyli/zju-connect#31]
2023/09/21 11:17:58 Login Request: https://vpn.shou.edu.cn:443/por/login_auth.csp?apiversion=1

2023/09/21 11:17:58 Twf Id: 7101f04fe61b52bb
2023/09/21 11:17:58 RSA Key: C5622DC9C719567A2F84F19F3C1FAB9C392264AF3FF6D1D7EB40D75D6D2E94245444F54544F3F33A67A90AAC3DB8A21528CA87DB3EB8AA05D22C471C4DB8F9FF9EBD801CE8EF7DB167E3C792D340AAA8DEDCAB4567D5254FB5F681B414BE50C5AC7C494A91D8C3AAD4EFEB7F28717F17844B2B2190A6A890AE8C180A9B72BCFD7325D077D37C46CF6FCB56B0BB0255BD57193DBA4D0F005053B3C560E6ADD9BC06D0EE1F03E86E5233D2F71727D56E3ED076B66BC980A145582591DFE0B381FC84542A9276B8FB6D6D7574A720C7F288B22C0CAEFF6F15E217CCDF0F990A0981F3A23540627B372AB5B6F20800DD9E1546804E20EA68962CDA3A39423F9DF68F
2023/09/21 11:17:58 RSA Exp: 65537
2023/09/21 11:17:58 WARNING: No CSRF Code Match. Maybe you're connecting to an older server? Continue anyway...
2023/09/21 11:17:58 Login Request: https://vpn.shou.edu.cn:443/por/login_psw.csp?anti_replay=1&encrypt=1&type=cs

2023/09/21 11:17:58 No NextAuth found.
2023/09/21 11:17:58 Web Login process done.

2023/09/21 11:17:58 ECAgent Request: /por/conf.csp & /por/rclist.csp

2023/09/21 11:17:58 Server Session ID: 48bcd60083c0e921136f965138b7589941a14585e39c3b388c074d47f5827ca3

2023/09/21 11:17:58 Parsed /por/conf.csp 

2023/09/21 11:17:58 Parsed /por/rclist.csp 
2023/09/21 11:17:58 try parsing by goXml
2023/09/21 11:17:58 Progress: 0/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 0/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 0/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 1/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 1/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 2/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 2/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 3/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 3/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 3/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 4/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 4/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 5/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 5/100 (ResourceList.Rcs)

2023/09/21 11:17:58 Progress: 6/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 6/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 7/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 7/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 7/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 8/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 8/100 (ResourceList.Rcs)

2023/09/21 11:17:58 Progress: 9/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 9/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 10/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 10/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 11/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 11/100 (ResourceList.Rcs)

2023/09/21 11:17:58 Progress: 11/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 12/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 12/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 13/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 13/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 14/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 14/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 14/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 15/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 15/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 16/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 16/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 17/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 17/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 18/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 18/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 18/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 19/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 19/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 20/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 20/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 21/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 21/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 22/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 22/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 22/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 23/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 23/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 24/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 24/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 25/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 25/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 25/100 (ResourceList.Rcs)

2023/09/21 11:17:58 Progress: 26/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 26/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 27/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 27/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 28/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 28/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 29/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 29/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 29/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 30/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 30/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 31/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 31/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 32/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 32/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 33/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 33/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 33/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 34/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 34/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 35/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 35/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 36/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 36/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 37/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 37/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 37/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 38/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 38/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 39/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 39/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 40/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 40/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 40/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 41/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 41/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 42/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 42/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 43/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 43/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 44/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 44/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 44/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 45/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 45/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 46/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 46/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 47/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 47/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 48/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 48/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 48/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 49/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 49/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 50/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 50/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 51/100 (ResourceList.Rcs)

2023/09/21 11:17:58 Progress: 51/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 51/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 52/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 52/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 53/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 53/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 54/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 54/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 55/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 55/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 55/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 56/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 56/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 57/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 57/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 58/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 58/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 59/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 59/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 59/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 60/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 60/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 61/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 61/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 62/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 62/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 62/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 63/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 63/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 64/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 64/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 65/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 65/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 66/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 66/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 66/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 67/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 67/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 68/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 68/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 69/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 69/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 70/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 70/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 70/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 71/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 71/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 72/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 72/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 73/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 73/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 74/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 74/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 74/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 75/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 75/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 76/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 76/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 77/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 77/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 77/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 78/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 78/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 79/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 79/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 80/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 80/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 81/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 81/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 81/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 82/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 82/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 83/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 83/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 84/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 84/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 85/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 85/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 85/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 86/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 86/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 87/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 87/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 88/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 88/100 (ResourceList.Rcs)

2023/09/21 11:17:58 Progress: 88/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 89/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 89/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 90/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 90/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 91/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 91/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 92/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 92/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 92/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 93/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 93/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 94/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 94/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 95/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 95/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 96/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 96/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 96/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 97/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 97/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 98/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 98/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 99/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Progress: 99/100 (ResourceList.Rcs)
2023/09/21 11:17:58 Parsed 865 domain rules
2023/09/21 11:17:58 Parsed 5 IPv4 rules
2023/09/21 11:17:58 Parsed 95 DNS rules

2023/09/21 11:17:58 socket: connected to:  58.246.161.76:443
2023/09/21 11:17:58 tls: connected to:  58.246.161.76:443

2023/09/21 11:17:58 Login success, your IP: 172.18.217.155

2023/09/21 11:17:58 SOCKS5 server listening on 127.0.0.1:1080
2023/09/21 11:17:58 HTTP server listening on 127.0.0.1:1081

2023/09/21 11:17:58 socket: connected to:  58.246.161.76:443
2023/09/21 11:17:58 tls: connected to:  58.246.161.76:443
2023/09/21 11:17:58 socket: connected to:  58.246.161.76:443

2023/09/21 11:17:58 tls: connected to:  58.246.161.76:443

2023/09/21 11:18:08 KeepAlive: lookup www.baidu.com on 192.168.5.1:53: read udp 172.18.217.155:32481: i/o timeout

2023/09/21 11:18:10 Error occurred while receiving, retrying: EOF

2023/09/21 11:18:10 socket: connected to:  58.246.161.76:443
2023/09/21 11:18:10 tls: connected to:  58.246.161.76:443

2023/09/21 11:18:10 Error occurred while receiving, retrying: unexpected recv handshake reply

2023/09/21 11:18:10 socket: connected to:  58.246.161.76:443
2023/09/21 11:18:10 tls: connected to:  58.246.161.76:443

2023/09/21 11:18:10 Error occurred while receiving, retrying: unexpected recv handshake reply

2023/09/21 11:18:10 socket: connected to:  58.246.161.76:443
2023/09/21 11:18:10 tls: connected to:  58.246.161.76:443

2023/09/21 11:18:10 Error occurred while receiving, retrying: unexpected recv handshake reply

2023/09/21 11:18:10 socket: connected to:  58.246.161.76:443
2023/09/21 11:18:10 tls: connected to:  58.246.161.76:443

2023/09/21 11:18:10 Error occurred while receiving, retrying: unexpected recv handshake reply

panic: receive retry limit exceeded.

goroutine 60 [running]:

github.com/mythologyli/zju-connect/core.StartProtocol.func1()
	github.com/mythologyli/zju-connect/core/protocol.go:231 +0x105
created by github.com/mythologyli/zju-connect/core.StartProtocol
	github.com/mythologyli/zju-connect/core/protocol.go:234 +0xd2

**Comment by Mythologyli** [comment]
使用命令行版，禁用 keep alive 试试

**Comment by Mythologyli** [comment]
初步判断问题原因为：GUI 版默认启用 keep alive，keep alive 需要进行 DNS 解析，由于 #32 导致出错
#33 应该可以解决

**Comment by Mythologyli** [comment]
10.10.0.21 UDP53 似乎可以正常解析了，理论上不会再出现此问题
