### ISSUE TITLE
校外VPN连接访问服务器

### ISSUE THREAD

**Issue by Master-PLC** [Mythologyli/zju-connect#37]
设置了端口转发，此前是能够通过一样的端口转发tcp连接校内服务器的，但是这两天通过转发的本地端口ssh的时候出现
ep.GetRemoteAddress() failed: endpoint not connected
想问一下有什么原因吗

**Comment by Mythologyli** [comment]
信息技术中心在亚运期间进行了限制，大部分服务器无法通过 RVPN 访问

**Comment by Master-PLC** [comment]
谢谢，有什么替代的解决方案吗

**Comment by Mythologyli** [comment]
通过学校的 RVPN 无法解决，如果服务器有 IPv6 可以尝试 IPv6 访问

**Comment by Master-PLC** [comment]
好的，感谢~
