### ISSUE TITLE
HTTP 代理可能存在问题

### ISSUE THREAD

**Issue by Mythologyli** [Mythologyli/zju-connect#39]
https://www.cc98.org/topic/5708120

当使用 zju-connect 内置的 http 代理时，进行统一身份认证时可能出现界面加载问题：
![image](https://github.com/Mythologyli/zju-connect/assets/15955880/15fd3b7d-42c4-40f3-9560-ebe4d6ad9300)

使用学在浙大测试发现，该现象不是每次都出现，反复登录-注销有几率触发。有时表现为界面加载不全，有时表现为无限重定向；使用 Clash + 内置 SOCKS5 代理，不会出现此现象

目前原因未知，怀疑 http 代理的实现可能存在问题

**Comment by cxz66666** [comment]
之前用zju connect的http proxy测试 appservice.zju.edu.cn 的时候也触发过，刷新几次好像就行了，后面可以多测试下
