### ISSUE TITLE
endpoint not connected

### ISSUE THREAD

**Issue by TTXS123OK** [Mythologyli/zju-connect#40]
在校外启动了 zju-connect 服务之后 ssh 连接校内服务器，出现如下报错
ep.GetRemoteAddress() failed: endpoint not connected
请问是什么问题？
---------------------------------------------------------------------------------
● zju-connect.service - ZJU Connect
     Loaded: loaded (/lib/systemd/system/zju-connect.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-09-27 16:38:28 CST; 1h 51min ago
   Main PID: 225 (zju-connect)
      Tasks: 11 (limit: 19019)
     Memory: 26.6M
     CGroup: /system.slice/zju-connect.service
             └─225 /opt/zju-connect -config /etc/zju-connect/config.toml

Sep 27 18:24:40 ThinkBook16pYGY zju-connect[225]: 2023/09/27 18:24:40 KeepAlive: OK
Sep 27 18:25:40 ThinkBook16pYGY zju-connect[225]: 2023/09/27 18:25:40 KeepAlive: OK
Sep 27 18:26:40 ThinkBook16pYGY zju-connect[225]: 2023/09/27 18:26:40 KeepAlive: OK
Sep 27 18:27:40 ThinkBook16pYGY zju-connect[225]: 2023/09/27 18:27:40 KeepAlive: OK
Sep 27 18:28:40 ThinkBook16pYGY zju-connect[225]: 2023/09/27 18:28:40 KeepAlive: OK
Sep 27 18:29:40 ThinkBook16pYGY zju-connect[225]: 2023/09/27 18:29:40 KeepAlive: OK
Sep 27 18:29:40 ThinkBook16pYGY zju-connect[225]: 2023/09/27 18:29:40 10.214.199.98:2333 -> PROXY
Sep 27 18:29:40 ThinkBook16pYGY zju-connect[225]: W0927 18:29:40.385609     225 gonet.go:457] ep.GetRemoteAddress() failed: endpoint not connected
Sep 27 18:29:40 ThinkBook16pYGY zju-connect[225]: W0927 18:29:40.386050     225 gonet.go:457] ep.GetRemoteAddress() failed: endpoint not connected
Sep 27 18:29:40 ThinkBook16pYGY zju-connect[225]: 2023/09/27 18:29:40 [E]: server: readfrom tcp 127.0.0.1:1080->127.0.0.1:36804: read tcp 10.190.64.201:57124: connection reset by peer

**Comment by Mythologyli** [comment]
看置顶：#37
