### ISSUE TITLE
期待能提供ssh隧道代理功能

### ISSUE THREAD

**Issue by Coldfengzi** [Mythologyli/zju-connect#42]
---

**软件版本**
v0.4.0

**使用环境**
Windows 10 x64

**服务端地址**
****:443

**功能请求描述** (建议结合图片说明)
在 https://github.com/Mythologyli/zju-connect/issues/9 已经提出过类似需求，确实现在可以用端口映射功能解决。但每次都需要映射也确实麻烦。期望能提供ssh隧道功能。
![image](https://github.com/Mythologyli/zju-connect/assets/23092924/226dd2a9-3e0d-4ab2-9de9-e3f8dc939b0c)

**Comment by Mythologyli** [comment]
没有太理解为什么需要在这个软件中实现此功能，可以解释详细一点吗？

按照我的理解，你应该把远程机器的 ssh 端口映射到本地，然后在 navicat ssh 隧道中配置为 127.0.0.1:xx

如果把配置文件写好的话，感觉也不是很麻烦？

**Comment by Coldfengzi** [comment]
> 没有太理解为什么需要在这个软件中实现此功能，可以解释详细一点吗？
> 
> 按照我的理解，你应该把远程机器的 ssh 端口映射到本地，然后在 navicat ssh 隧道中配置为 127.0.0.1:xx
> 
> 如果把配置文件写好的话，感觉也不是很麻烦？

因为远程机器必须要用easyconnect去连。远程机器上的应用比较多，每个端口都开的话也确实麻烦。如果用配置文件，需要更改一个端口，就必须要重启[zju-connect](https://github.com/Mythologyli/zju-connect)，而虚拟隧道的话就不需要；而且开通了虚拟隧道的话，不止在navicat中可以用，其他软件也可以用到的。总之多一种代理方式吧。

**Comment by Mythologyli** [comment]
那你按照我说的方法，把远程机器的 ssh 端口转发到本地不就行了

**Comment by Mythologyli** [comment]
并且 socks5 的通用性显然比 ssh 隧道强吧，理论上来说配置其他应用使用 socks5 代理应该更方便才对

**Comment by Coldfengzi** [comment]
1、数据库比较多，用ssh端口转发还需要先打开xshell，并且还要配置隧道。数据库多的情况下，很有可能会冲突。并且使用的人可能并不是我。还有其他同事。用端口转发还得每个人教一次；
2、确实有socks 5已经很方便了，奈何navicat、jumpserver这种他不支持socks啊。

**Comment by Mythologyli** [comment]
所以你想要的是一个类似于 VPN 的功能吗？启用后在本地创建一个网卡，然后配置路由规则，像 easyconnect 一样

**Comment by Coldfengzi** [comment]
> 所以你想要的是一个类似于 VPN 的功能吗？启用后在本地创建一个网卡，然后配置路由规则，像 easyconnect 一样
不是的，就是类似socks5 ，用户名、密码都是socks5的用户名密码，然后navicat可以
![image](https://github.com/Mythologyli/zju-connect/assets/23092924/0e797c7d-4f12-453e-988e-0c9725d98c1e)
连就可以了

**Comment by cxz66666** [comment]
我大概理解了，你是希望有一个本地的端口 localhost:port，每次写ssh隧道/-J的时候主机和端口设置成localhost:port一样就行，使用体验类似，是这个意思吗

**Comment by Mythologyli** [comment]
> > 所以你想要的是一个类似于 VPN 的功能吗？启用后在本地创建一个网卡，然后配置路由规则，像 easyconnect 一样
> 不是的，就是类似socks5 ，用户名、密码都是socks5的用户名密码，然后navicat可以
> ![image](https://github.com/Mythologyli/zju-connect/assets/23092924/0e797c7d-4f12-453e-988e-0c9725d98c1e)
> 连就可以了

那按理说你就像我之前说的那样，把远程 ssh 端口转发到本地，然后改一下你这张图中的主机和端口不就行了

**Comment by Coldfengzi** [comment]
好吧，类似功能的模块我在github上也没发现，实现起来估计难度也比较大，还是作罢吧。
