### ISSUE TITLE
无法关闭http&socks代理

### ISSUE THREAD

**Issue by Coldfengzi** [Mythologyli/zju-connect#43]
---

**软件版本**
v0.4.1

**使用环境**
CentOS 8
**服务端地址**
****:443

**故障描述** (建议结合图片说明)
查看代码发现，http代理和sockts代理无法关闭（只想保留端口转发）

**重现方法**
https://github.com/Mythologyli/zju-connect/blob/9b799a4f87074778eb62a3c7da88e0addd2aed2d/core/http.go#L64C27-L64C33
无控制开关

**预期行为**
根据socks_bind，http_bind配置为空则不开启监听

**日志**
```
在此粘贴
```

**配置文件或启动参数** (请去除敏感信息)
```
在此粘贴
```

**Comment by Mythologyli** [comment]
目前 http 代理配置为空可以关闭，socks5 代理暂时不可关闭

**Comment by Mythologyli** [comment]
等有空的时候我修改一下逻辑

不过现在 http 代理依赖 socks5 代理，意味着后者关闭前者无法正常运行

**Comment by Mythologyli** [comment]
请测试：https://github.com/Mythologyli/zju-connect/actions/runs/6440503537
