### ISSUE TITLE
自定义走代理的域名

### ISSUE THREAD

**Issue by Long0x0** [Mythologyli/zju-connect#53]
**软件版本**
v0.7.0

**使用环境**
Windows 11 x64

**服务端地址**
rvpn.zju.edu.cn:443

**功能请求描述** 
支持自定义走代理的域名，例如www.science.org，是不是RVPN没有内置这个域名规则，只有开-proxy-all才能正常访问
https://www.cc98.org/topic/5813839/1

**Comment by cxz66666** [comment]
感觉合理，可以加一个custom proxy domain的配置，然后 domainResource中加上就行

**Comment by Mythologyli** [comment]
我有空加一下
