### ISSUE TITLE
连不上校园网

### ISSUE THREAD

**Issue by yym68686** [Mythologyli/zju-connect#56]
**提交之前**

在提交报告之前，请确保：
+ 你正在使用 [Release](https://github.com/Mythologyli/zju-connect/releases) 中的最新版本
+ 如果你可以访问 CC98，请确保你已经阅读过以下说明：
    + [使用 ZJU Connect 代替 EasyConnect 提升你的 RVPN 体验](https://www.cc98.org/topic/5521873)
    + [端口转发、定时保活、自动选线、密码保存](https://www.cc98.org/topic/5570875)
+ 你已搜索过现有的 [Issues](https://github.com/Mythologyli/zju-connect/issues?q=is%3Aissue) 并且未发现重复

**确认无误后，请删除下方横线及以上内容。之后，请修改下方的模版并提交报告**

---

**软件版本**
v0.7.0

**使用环境**
MacBook Pro Docker

**服务端地址**
rvpn.zju.edu.cn:443

**故障描述** (建议结合图片说明)
<img width="786" alt="image" src="https://github.com/Mythologyli/zju-connect/assets/31803242/b065e7b7-9231-4587-b608-2b7d7e1c809d">

无法连接校园网，cc98 上不了。

**重现方法**

**预期行为**
能上cc98

**日志**
```
2024/04/15 03:48:12 Start ZJU Connect v0.7.0
2024/04/15 03:48:12 Request: https://rvpn.zju.edu.cn:443/por/login_auth.csp?apiversion=1
2024/04/15 03:48:13 TWFID: 23942fa75d262cab
2024/04/15 03:48:13 RSA key: A41BEB76968C21EA9174095B98E1856A54EE005C6CE9A1B13D3C8EA72F71FACBA6D92DADCACE91DEA27227A311DC48FA2B90E4ACA003D8A48D694A8E56517D5CABC4B9A00BAD3B5010430C968916155E746D14C01D31CF155B906389C906F9B12B942639FD3B3E31EFB25CE142EFB4C4DB95686750685A6866FEFD6A2A716A92D837061A0070AEF6C8D7FB6D5ECD03AC39E0FF32EFDB644639E279382799F34E75B86BBB3D8859A7FA5E63B4FF56CFD59035C71A523FE34CC97C78426B7E73A449356E4B21DBF45E6CF1182DC5999D9E15CEEE3A6DC22BAC3BDBA094CDAACF198315C24A1927BCB98CEE77530C0B43ED0784F139D1D87C89E33B39439C7B7F99
2024/04/15 03:48:13 RSA exp: 65537
2024/04/15 03:48:13 Warning: No CSRF rand code
2024/04/15 03:48:13 Request: https://rvpn.zju.edu.cn:443/por/login_psw.csp?anti_replay=1&encrypt=1&type=cs
```

**配置文件或启动参数** (请去除敏感信息)
```
username = ""
password = ""

# Advanced settings
server_address = "rvpn.zju.edu.cn"
server_port = 443
disable_server_config = false
disable_zju_config = false
disable_zju_dns = false
disable_multi_line = false
proxy_all = false
socks_bind = ":1080"
socks_user = ""
socks_passwd = ""
http_bind = ":1081"
dns_ttl = 3600
disable_keep_alive = false
zju_dns_server = "10.10.0.21"
debug_dump = false
```

**Comment by Mythologyli** [comment]
mac 使用需要设置系统 socks 代理，你设置了嘛

**Comment by yym68686** [comment]
设置了。surge 增强模式。
分流规则：
```
[Proxy]
zjusocks=socks5,127.0.0.1,1080
zjuhttp=http,127.0.0.1,1081
```

分流脚本
```
[Script]
zju-script-ming = type=rule,script-path=zju-ming.js
zju-script-zjuwifi = type=rule,script-path=zju-zjuwifi.js
```
zju-ming.js 细节(这是我连接手机热点时的分流js脚本)
```
console.log($network)
// console.log($network.dns[0].startsWith('172.20.10'))
var hostnameMatched = (
	$request.hostname.endsWith('zju.edu.cn') || 
    $request.hostname.endsWith('cc98.org') || 
	$request.hostname.startsWith('10.214.') ||
	$request.hostname.startsWith('10.10.') ||
	$request.hostname.endsWith('cqvip.com')
);
var ssidMatched = !$network.dns[0].startsWith('10');

console.log($request.hostname + "匹配吗？" + hostnameMatched)
console.log("不在zju吗？" + ssidMatched)
console.log(hostnameMatched && ssidMatched)
$done({matched: (hostnameMatched && ssidMatched)});
```

**Comment by cxz66666** [comment]
日志看起来像执行到Request: https://rvpn.zju.edu.cn:443/por/login_psw.csp?anti_replay=1&encrypt=1&type=cs 这里卡住了，请问你使用浏览器能访问这一串url吗

**Comment by yym68686** [comment]
可以，但只显示一串字符串：
<img width="687" alt="image" src="https://github.com/Mythologyli/zju-connect/assets/31803242/f53b4683-6261-4b6a-9aae-06f8e88d9f8a">

**Comment by cxz66666** [comment]
已在最新版zju-connect的 macos版复现，初步推测rvpn服务器抽风，等待进一步排查，

**Comment by yym68686** [comment]
谢谢，那请问 macOS 还有其他网址(SSL VPN 服务端地址)可以请求或者其他方法目前能连上校园网吗？

**Comment by cxz66666** [comment]
排查了下，看起来像是公网的rvpn server出问题了，关闭自动选线(diable_multi_line)后，使用校内的10.3.1.170可以正常连接，但是使用下发的61.175和218.108 server进行测试就会出现上述问题，只能等待rvpn server赶紧修复了。

> 谢谢，那请问 macOS 还有其他网址(SSL VPN 服务端地址)可以请求或者其他方法目前能连上校园网吗？

只有网页需求的话可以试试webvpn.zju.edu.cn

**Comment by Mythologyli** [comment]
【电脑医院】学校的的rvpn服务器是不是挂了 https://www.cc98.org/topic/5865752

应该是服务器问题

**Comment by Mythologyli** [comment]
> 谢谢，那请问 macOS 还有其他网址(SSL VPN 服务端地址)可以请求或者其他方法目前能连上校园网吗？

可以用 webvpn，还可以看看[这个](https://github.com/Mythologyli/websocket-via-webvpn)，不过需要预先配置

**Comment by yym68686** [comment]
谢谢，rvpn 已经恢复了。
