### ISSUE TITLE
clash tun模式配合下游zjuconnect，当clash分流错误时会死循环

### ISSUE THREAD

**Issue by cxz66666** [Mythologyli/zju-connect#57]
**软件版本**
latest

**使用环境**
Windows 10 x64

**服务端地址**
rvpn.zju.edu.cn:443

**故障描述** (建议结合图片说明)

windows下使用clash tun模式作为流量入口，分流规则中接入下游的zjuconnect，zjuconnect使用socks/http监听1080端口

当clash分流规则错误，将类似baidu.com等需要直连的网站转发至zjuconnect时，zjuconnect会使用dialDirectWithoutProxy直接访问，然而这次访问会被clashtun模式接管，然后继续转发到zjuconnect，形成死循环。

虽然该bug是由clash分流配置错误引起的，但是zjuconnect能否检测/并及时提示反馈给用户；或者直接将包注入指定的网卡，不使用现在这种普通的DialContext；或者我们还是应该维持现在的逻辑，用户配置错误用户自己买单。

![image](https://github.com/user-attachments/assets/a2295edc-39af-437e-8898-69643c06faf5)

**Comment by Mythologyli** [comment]
检测的话感觉没有什么必要，我觉得文档里面提醒一下就可以。绑定到端口可以作为一个功能来实现，到时候可以在文档里提一下绑定到端口也可以解决上述问题

**Comment by cxz66666** [comment]
有道理，我后面更新一下文档中Tun mode注意事项
