### ISSUE TITLE
docker 镜像能否使用 root 用户

### ISSUE THREAD

**Issue by futuretech6** [Mythologyli/zju-connect#61]
现在的镜像使用的是 nonroot 镜像作为 prd 层，这会导致 host 的 config.toml 为 600 时，容器中的 nonroot (65532:65532) 无权限访问映射进容器的 config.toml，报错 `ZJU Connect: error parsing the config file`，如果容器中的用户为 root 的话，则不存在这个问题。

使用 nonroot 是出于安全考虑吗，我目前还想不到这会导致什么安全问题（除非其他 docker 组成员 exec 了这个容器并修改 config 内容，但是这个条件太苛刻了）。

**Comment by Mythologyli** [comment]
欢迎 @117503445 一起来讨论

**Comment by futuretech6** [comment]
> 使用nonroot应该还是为了最小化权限需求，至于提到的600问题感觉有些小众，需要额外chmod。如果确实有需求可以自己docker build . 一波

主要我想了想，感觉 nonroot 和 root 在 zju-connect 的场景下没啥区别，没有用 `--privileged` 启动的话也不存在逃逸的问题 🤔

**Comment by futuretech6** [comment]
> 至于提到的600问题感觉有些小众，需要额外chmod

我用 https://github.com/abraunegg/onedrive 在 linux 上同步我的一些配置文件，然后这东西下载的东西就是 600 的 🤣

**Comment by cxz66666** [comment]
> 然后这东西下载的东西就是 600 的 🤣
合理，支持改成gcr.io/distroless/static，nonroot防的潜在的CVE应该也问题不大(X

**Comment by 117503445** [comment]
+1，我觉得改成 root 用户也没什么问题。

nonroot 用户带来的安全性提升并不显著，但却降低了使用的便捷性。

**Comment by cxz66666** [comment]
已修改并测试，为了后向配置文件兼容性还是用了/home/nonroot的路径
@Mythologyli  BTW，现在的action是不是挂了

**Comment by 117503445** [comment]
> 已修改并测试，为了后向配置文件兼容性还是用了/home/nonroot的路径 @Mythologyli BTW，现在的action是不是挂了

似乎是 `.github/workflows/docker.yml` 没有命中 on 的条件

可以给 `on.push.paths` 添加上 `Dockerfile`

**Comment by Mythologyli** [comment]
CI 问题已修复 384f1dc701115dfde0ee49f30a693bbb9240f44b

**Comment by futuretech6** [comment]
测试了 `mythologyli/zju-connect:sha-384f1dc`，可以实现预期效果 :heart:
